### PR TITLE
Update UI.Frame.pas

### PR DESCRIPTION
**Pull request by marlonnardi**
Fix error operation not alowed in Android and IOS

### CODE REVIEW

**Comment by KngStr** [comment]
Thanks.

Your forgot about `HideWaitDialog`.
WaitDialog likes Hint, thread safe is not bad.

PS: This is not error,  Delphi is just not allowed to be run in thread.

**Comment by marlonnardi** [comment]
yes I am identifying other errors now in IOS, we will have to analyze it better
image

**Comment by KngStr** [comment]
Please confirm your code of UI is running in the main thread.

**Comment by marlonnardi** [comment]
> Thanks.
> 
> Your forgot about `HideWaitDialog`.
> WaitDialog likes Hint, thread safe is not bad.
> 
> PS: This is not error, 'UI Code' is just not allowed to be run in thread.

Exactly, HideWaitDialog was missing, fixed for Android and IOS

**Comment by KngStr** [comment]
Thanks.

**Pull request merged**
